package com.myspace.digitalrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonalDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyHolderDOB")
	private java.util.Date policyHolderDOB;

	@org.kie.api.definition.type.Label("licenseAppliedDate")
	private java.util.Date licenseAppliedDate;

	@org.kie.api.definition.type.Label(value = "policyHolderMaritualStatusCode")
	private java.lang.String policyHolderMaritualStatusCode;

	@org.kie.api.definition.type.Label(value = "memberRelationToPolicyHolderCode")
	private java.lang.String memberRelationToPolicyHolderCode;

	public PersonalDetails() {
	}

	public java.util.Date getPolicyHolderDOB() {
		return this.policyHolderDOB;
	}

	public void setPolicyHolderDOB(java.util.Date policyHolderDOB) {
		this.policyHolderDOB = policyHolderDOB;
	}

	public java.util.Date getLicenseAppliedDate() {
		return this.licenseAppliedDate;
	}

	public void setLicenseAppliedDate(java.util.Date licenseAppliedDate) {
		this.licenseAppliedDate = licenseAppliedDate;
	}

	public java.lang.String getPolicyHolderMaritualStatusCode() {
		return this.policyHolderMaritualStatusCode;
	}

	public void setPolicyHolderMaritualStatusCode(
			java.lang.String policyHolderMaritualStatusCode) {
		this.policyHolderMaritualStatusCode = policyHolderMaritualStatusCode;
	}

	public java.lang.String getMemberRelationToPolicyHolderCode() {
		return this.memberRelationToPolicyHolderCode;
	}

	public void setMemberRelationToPolicyHolderCode(
			java.lang.String memberRelationToPolicyHolderCode) {
		this.memberRelationToPolicyHolderCode = memberRelationToPolicyHolderCode;
	}

	public PersonalDetails(java.util.Date policyHolderDOB,
			java.util.Date licenseAppliedDate,
			java.lang.String policyHolderMaritualStatusCode,
			java.lang.String memberRelationToPolicyHolderCode) {
		this.policyHolderDOB = policyHolderDOB;
		this.licenseAppliedDate = licenseAppliedDate;
		this.policyHolderMaritualStatusCode = policyHolderMaritualStatusCode;
		this.memberRelationToPolicyHolderCode = memberRelationToPolicyHolderCode;
	}

}