package com.myspace.digitalrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PolicyDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("portableInsuredValue")
	private java.lang.Integer portableInsuredValue;

	@org.kie.api.definition.type.Label("homeContentsInsuredValue")
	private java.lang.Integer homeContentsInsuredValue;

	@org.kie.api.definition.type.Label("errors")
	private java.util.List<com.myspace.digitalrules.error> errors;

	@org.kie.api.definition.type.Label("lightningConductorOption")
	private java.lang.Boolean lightningConductorOption;

	@org.kie.api.definition.type.Label("thrashedroof")
	private java.lang.Boolean thrashedroof;

	@org.kie.api.definition.type.Label(value = "personalDetails")
	private com.myspace.digitalrules.PersonalDetails personalDetails;

	public PolicyDetails() {
	}

	public java.lang.Integer getPortableInsuredValue() {
		return this.portableInsuredValue;
	}

	public void setPortableInsuredValue(java.lang.Integer portableInsuredValue) {
		this.portableInsuredValue = portableInsuredValue;
	}

	public java.lang.Integer getHomeContentsInsuredValue() {
		return this.homeContentsInsuredValue;
	}

	public void setHomeContentsInsuredValue(
			java.lang.Integer homeContentsInsuredValue) {
		this.homeContentsInsuredValue = homeContentsInsuredValue;
	}

	public java.util.List<com.myspace.digitalrules.error> getErrors() {
		return this.errors;
	}

	public void setErrors(java.util.List<com.myspace.digitalrules.error> errors) {
		this.errors = errors;
	}

	public java.lang.Boolean getLightningConductorOption() {
		return this.lightningConductorOption;
	}

	public void setLightningConductorOption(
			java.lang.Boolean lightningConductorOption) {
		this.lightningConductorOption = lightningConductorOption;
	}

	public java.lang.Boolean getThrashedroof() {
		return this.thrashedroof;
	}

	public void setThrashedroof(java.lang.Boolean thrashedroof) {
		this.thrashedroof = thrashedroof;
	}

	public com.myspace.digitalrules.PersonalDetails getPersonalDetails() {
		return this.personalDetails;
	}

	public void setPersonalDetails(
			com.myspace.digitalrules.PersonalDetails personalDetails) {
		this.personalDetails = personalDetails;
	}

	public PolicyDetails(java.lang.Integer portableInsuredValue,
			java.lang.Integer homeContentsInsuredValue,
			java.util.List<com.myspace.digitalrules.error> errors,
			java.lang.Boolean lightningConductorOption,
			java.lang.Boolean thrashedroof,
			com.myspace.digitalrules.PersonalDetails personalDetails) {
		this.portableInsuredValue = portableInsuredValue;
		this.homeContentsInsuredValue = homeContentsInsuredValue;
		this.errors = errors;
		this.lightningConductorOption = lightningConductorOption;
		this.thrashedroof = thrashedroof;
		this.personalDetails = personalDetails;
	}

}